services:
  api-gateway:
    build:
      context: ./apps/api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      SECRET_WORD: ${SECRET_WORD}
    restart: always