services:
  # Service PostgreSQL
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: tickly
      POSTGRES_PASSWORD: ticklypassword
      POSTGRES_DB: tickly_db
    ports:
      - '5000:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tickly-network

  # Service RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5673:5672'  # Broker
      - '15673:15672' # Interface web
    networks:
      - tickly-network

volumes:
  postgres_data:

networks:
  tickly-network:
    driver: bridge